### ISSUE TITLE
Show USD value to the amount burned!

### ISSUE THREAD

**Issue by mohamedmansour** [mohamedmansour/eth-burn#5]
Would be nice to show the USD value. One way to make this happen is to have a cronjob running to get access to current prices and store them in a json file in the same web location. We don't have a backend, just a connection to Geth

**Comment by perama-v** [comment]
Another way might be to ping an on-chain TWAP ETH-USD price oracle

**Comment by mohamedmansour** [comment]
Hi @perama-v is there an example? That sounds pretty good, do you have a contract address? Does that contract live in testnet?

**Comment by perama-v** [comment]
I don't think it would work for Calaveras (no AMMs), but it looks like you plan is to follow the forks. 
For Ropsten, you could start querying for the price, although the price will be wrong because it's testnet money (e.g., 
current WETH/DAI [rate is ~500 DAI/WETH](https://ropsten.etherscan.io/tx/0x35f8166a5fd2e9da31825803fe96a3085c96de9a30b84ccc76e483aa7c9a73a0)).

So it really doesn't add any value until mainnet. If it's your plan to run it on mainnet, then you could pull the data
and not reveal it on the front end until mainnet forks.

- Uniswap v3 [SDK](https://docs.uniswap.org/SDK-guides/using-ethers) with ethers.js.
- Call to [token0price](https://docs.uniswap.org/SDK/classes/Pool#token0price) for the WETH/DAI pair
- A note on calculating the price from the ticks [here](https://docs.uniswap.org/concepts/V3-overview/oracle#observations)
- I found some steps outlined by Quicknode [here](https://www.quicknode.com/guides/defi/how-to-interact-with-uniswap-using-javascript) that may work.

At which point it would just be calling to your Geth mainnet node. 

Just a thought anyway!

**Comment by mohamedmansour** [comment]
This is now implemented in the main page:
![image](https://user-images.githubusercontent.com/68524/123201130-f198ae80-d466-11eb-879e-cca9fb8309c8.png)
